name: al_hirfa
description: "منصة الحرفة للتراث العراقي"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - screen_2.html
    - screen_3.html
    - screen_4.html
    - screen_5.html
    - screen_6.html
    - screen_7.html
    - screen_8.html
    - screen_9.html
    - screen_10.html
    - screen_11.html
    - screen_12.html
    - screen_13.html
    - screen_14.html
